### ISSUE TITLE
Epic Refactor

### ISSUE THREAD

**Issue by baccenfutter** [blunix/role-slapd#16]
# Problem
This role really needs a rewrite. It is very old and badly outdated.

# Todos
* [ ] Create new Molecule `default` scenario
- [ ] Update all Python deps to latest
-  [ ] Rewrite all tasks and handlers to follow latest standards
- [ ] Rewrite all `olc*.ldif`scripts to use Ansbile-2.5+ LDAP modules
- [ ] Move all slapd configuration to `cn=config`
- [ ] Reimplement tests
